services:
  api:
    image: api
    build: 
      context: .
      dockerfile: ./api.Dockerfile
    command: run
    restart: unless-stopped
    network_mode: host 
  frontend:
    image: frontend
    build: 
      context: .
      dockerfile: ./frontend.Dockerfile
    restart: unless-stopped
    network_mode: host
  caddy:
    image: caddy:latest    
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    restart: unless-stopped
    environment:
      - HOST=http://website.local:80
      - CERT_PATH=
      - CONNECTION_STRING=
      - HOST_ADDRESS=
      - PORT=
volumes:
  caddy_data:


    
    


    
